import pyadb

pyadb.adb_path("/Users/error_063/Tools/adb工具/macos-adb/")
pyadb.device.connect("192.168.1.6","")
pyadb.device.list("self")
